/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2024-07-30 15:34:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html.portlets.dossiermgt.frontoffice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.liferay.portal.kernel.portlet.LiferayWindowState;
import javax.portlet.PortletRequest;
import com.liferay.portlet.PortletURLFactoryUtil;
import org.opencps.util.WebKeys;
import org.opencps.dossiermgt.model.DossierPart;
import org.opencps.dossiermgt.model.DossierFile;
import org.opencps.dossiermgt.search.DossierFileDisplayTerms;
import com.liferay.portal.kernel.language.UnicodeLanguageUtil;
import org.opencps.util.PortletConstants;
import org.opencps.util.DLFileEntryUtil;
import com.liferay.portal.kernel.repository.model.FileEntry;
import com.liferay.portlet.documentlibrary.util.DLUtil;
import com.liferay.portlet.documentlibrary.service.DLAppServiceUtil;
import org.opencps.dossiermgt.service.DossierFileLocalServiceUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portlet.PortletPreferencesFactoryUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.util.PortalUtil;
import com.liferay.portal.kernel.dao.search.SearchContainer;

public final class overview_005ffiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/init.jsp", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/html/portlets/dossiermgt/frontoffice/../init.jsp", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/opencps-dl-upload.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet-ext.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/opencps-datamgt.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-theme.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-util.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/aui.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-ui.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-security.tld", Long.valueOf(1722352539000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.release();
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse.release();
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write('\r');
      out.write('\n');

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  portlet:defineObjects
      com.liferay.taglib.portlet.DefineObjectsTag _jspx_th_portlet_005fdefineObjects_005f0 = (com.liferay.taglib.portlet.DefineObjectsTag) _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.get(com.liferay.taglib.portlet.DefineObjectsTag.class);
      _jspx_th_portlet_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_portlet_005fdefineObjects_005f0 = _jspx_th_portlet_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_portlet_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.reuse(_jspx_th_portlet_005fdefineObjects_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.reuse(_jspx_th_portlet_005fdefineObjects_005f0);
      javax.portlet.ActionRequest actionRequest = null;
      javax.portlet.ActionResponse actionResponse = null;
      javax.portlet.EventRequest eventRequest = null;
      javax.portlet.EventResponse eventResponse = null;
      com.liferay.portal.kernel.portlet.LiferayPortletRequest liferayPortletRequest = null;
      com.liferay.portal.kernel.portlet.LiferayPortletResponse liferayPortletResponse = null;
      javax.portlet.PortletConfig portletConfig = null;
      java.lang.String portletName = null;
      javax.portlet.PortletPreferences portletPreferences = null;
      java.util.Map portletPreferencesValues = null;
      javax.portlet.PortletSession portletSession = null;
      java.util.Map portletSessionScope = null;
      javax.portlet.RenderRequest renderRequest = null;
      javax.portlet.RenderResponse renderResponse = null;
      javax.portlet.ResourceRequest resourceRequest = null;
      javax.portlet.ResourceResponse resourceResponse = null;
      com.liferay.portal.kernel.util.SearchContainerReference searchContainerReference = null;
      actionRequest = (javax.portlet.ActionRequest) _jspx_page_context.findAttribute("actionRequest");
      actionResponse = (javax.portlet.ActionResponse) _jspx_page_context.findAttribute("actionResponse");
      eventRequest = (javax.portlet.EventRequest) _jspx_page_context.findAttribute("eventRequest");
      eventResponse = (javax.portlet.EventResponse) _jspx_page_context.findAttribute("eventResponse");
      liferayPortletRequest = (com.liferay.portal.kernel.portlet.LiferayPortletRequest) _jspx_page_context.findAttribute("liferayPortletRequest");
      liferayPortletResponse = (com.liferay.portal.kernel.portlet.LiferayPortletResponse) _jspx_page_context.findAttribute("liferayPortletResponse");
      portletConfig = (javax.portlet.PortletConfig) _jspx_page_context.findAttribute("portletConfig");
      portletName = (java.lang.String) _jspx_page_context.findAttribute("portletName");
      portletPreferences = (javax.portlet.PortletPreferences) _jspx_page_context.findAttribute("portletPreferences");
      portletPreferencesValues = (java.util.Map) _jspx_page_context.findAttribute("portletPreferencesValues");
      portletSession = (javax.portlet.PortletSession) _jspx_page_context.findAttribute("portletSession");
      portletSessionScope = (java.util.Map) _jspx_page_context.findAttribute("portletSessionScope");
      renderRequest = (javax.portlet.RenderRequest) _jspx_page_context.findAttribute("renderRequest");
      renderResponse = (javax.portlet.RenderResponse) _jspx_page_context.findAttribute("renderResponse");
      resourceRequest = (javax.portlet.ResourceRequest) _jspx_page_context.findAttribute("resourceRequest");
      resourceResponse = (javax.portlet.ResourceResponse) _jspx_page_context.findAttribute("resourceResponse");
      searchContainerReference = (com.liferay.portal.kernel.util.SearchContainerReference) _jspx_page_context.findAttribute("searchContainerReference");
      out.write('\n');
      out.write('\n');
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = (com.liferay.taglib.theme.DefineObjectsTag) _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.get(com.liferay.taglib.theme.DefineObjectsTag.class);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      com.liferay.portal.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.model.Company company = null;
      com.liferay.portal.model.Account account = null;
      com.liferay.portal.model.User user = null;
      com.liferay.portal.model.User realUser = null;
      com.liferay.portal.model.Contact contact = null;
      com.liferay.portal.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long scopeGroupId = null;
      com.liferay.portal.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.model.Theme theme = null;
      com.liferay.portal.model.ColorScheme colorScheme = null;
      com.liferay.portal.theme.PortletDisplay portletDisplay = null;
      java.lang.Long portletGroupId = null;
      themeDisplay = (com.liferay.portal.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.model.Company) _jspx_page_context.findAttribute("company");
      account = (com.liferay.portal.model.Account) _jspx_page_context.findAttribute("account");
      user = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      scopeGroupId = (java.lang.Long) _jspx_page_context.findAttribute("scopeGroupId");
      permissionChecker = (com.liferay.portal.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      out.write('\n');
      out.write('\n');

	String currentURL = PortalUtil.getCurrentURL(liferayPortletRequest);
	String keyword = ParamUtil.getString(request, "keywords", StringPool.BLANK);
	String templatePath = portletConfig.getInitParameter("template-path");
	
	String portletResource = ParamUtil.getString(request,"portletResource");
	
	if (Validator.isNotNull(portletResource)) {
		portletPreferences = PortletPreferencesFactoryUtil.getPortletSetup(request, portletResource);
	}

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

	//DossierFile dossierFile = (DossierFile) request.getAttribute(WebKeys.DOSSIER_FILE_ENTRY);

	DossierPart dossierPart = (DossierPart) request.getAttribute(WebKeys.DOSSIER_PART_ENTRY);
	
	long dossierPartId = ParamUtil.getLong(request, DossierFileDisplayTerms.DOSSIER_PART_ID);
	
	long dossierFileId = ParamUtil.getLong(request, DossierFileDisplayTerms.DOSSIER_FILE_ID);
	
	long fileEntryId = ParamUtil.getLong(request, DossierFileDisplayTerms.FILE_ENTRY_ID);
	
	int index = ParamUtil.getInteger(request, DossierFileDisplayTerms.INDEX);
	
	int level = ParamUtil.getInteger(request, DossierFileDisplayTerms.LEVEL);
	
	int partType = ParamUtil.getInteger(request, DossierFileDisplayTerms.PART_TYPE);
	
	String groupName = ParamUtil.getString(request, DossierFileDisplayTerms.GROUP_NAME);
	
	DossierFile dossierFile = null;
	
	if(dossierFileId > 0){
		try{
			dossierFile = DossierFileLocalServiceUtil.getDossierFile(dossierFileId);
		}catch(Exception e){
			
		}
	}
	
	String fileURL = StringPool.BLANK;
	
	if(dossierFile != null && dossierFile.getFileEntryId() > 0){
		FileEntry fileEntry = DLFileEntryUtil.getFileEntry(fileEntryId);
		if(fileEntry != null){
			fileURL = DLUtil.getPreviewURL(fileEntry, fileEntry.getFileVersion(), 
					themeDisplay, StringPool.BLANK);
		}
		
	}
		

      out.write('\n');
      out.write('\n');
      //  c:if
      com.liferay.taglib.core.IfTag _jspx_th_c_005fif_005f0 = (com.liferay.taglib.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(com.liferay.taglib.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(79,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(true );
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t<table width=\"100%\">\n");
        out.write("\t\t<tr>\n");
        out.write("\t\t\t");
        //  c:choose
        com.liferay.taglib.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (com.liferay.taglib.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(com.liferay.taglib.core.ChooseTag.class);
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f0 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(83,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_SUBMIT);
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t");
            //  aui:a
            com.liferay.taglib.aui.ATag _jspx_th_aui_005fa_005f0 = (com.liferay.taglib.aui.ATag) _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.get(com.liferay.taglib.aui.ATag.class);
            _jspx_th_aui_005fa_005f0.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fa_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f0.setId(String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) null
            _jspx_th_aui_005fa_005f0.setDynamicAttribute(null, "dossier-part", String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) null
            _jspx_th_aui_005fa_005f0.setDynamicAttribute(null, "dossier-file", String.valueOf(dossierFileId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) null
            _jspx_th_aui_005fa_005f0.setDynamicAttribute(null, "index", String.valueOf(index) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) null
            _jspx_th_aui_005fa_005f0.setDynamicAttribute(null, "group-name", groupName );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) null
            _jspx_th_aui_005fa_005f0.setDynamicAttribute(null, "level", level );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) name = href type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f0.setHref("javascript:void(0);");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f0.setLabel("view-form");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f0.setCssClass("opencps dossiermgt part-file-ctr view-form");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(85,6) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f0.setOnClick(renderResponse.getNamespace() + "viewForm(this)" );
            int _jspx_eval_aui_005fa_005f0 = _jspx_th_aui_005fa_005f0.doStartTag();
            if (_jspx_th_aui_005fa_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f0);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fa_0026_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f0);
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t");
            //  aui:a
            com.liferay.taglib.aui.ATag _jspx_th_aui_005fa_005f1 = (com.liferay.taglib.aui.ATag) _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.get(com.liferay.taglib.aui.ATag.class);
            _jspx_th_aui_005fa_005f1.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fa_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f1.setId(String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "dossier-part", String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "dossier-file", String.valueOf(dossierFileId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "file-url", fileURL );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "index", String.valueOf(index) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "group-name", groupName );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "level", level );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "file-name", dossierPart != null ? dossierPart.getPartName() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "part-type", partType );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) null
            _jspx_th_aui_005fa_005f1.setDynamicAttribute(null, "template-no", dossierPart != null ? dossierPart.getTemplateFileNo() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) name = href type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f1.setHref("javascript:void(0);");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f1.setLabel("view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f1.setCssClass("opencps dossiermgt part-file-ctr view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(100,6) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f1.setOnClick(renderResponse.getNamespace() + "viewAttachment(this)" );
            int _jspx_eval_aui_005fa_005f1 = _jspx_th_aui_005fa_005f1.doStartTag();
            if (_jspx_th_aui_005fa_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f1);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f1);
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f1 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(120,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f1.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_OTHER && level == 0 );
          int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
          if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t");
            //  aui:a
            com.liferay.taglib.aui.ATag _jspx_th_aui_005fa_005f2 = (com.liferay.taglib.aui.ATag) _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.get(com.liferay.taglib.aui.ATag.class);
            _jspx_th_aui_005fa_005f2.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fa_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f2.setId(String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "dossier-part", String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "dossier-file", String.valueOf(dossierFileId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "file-url", fileURL );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "index", String.valueOf(index) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "group-name", groupName );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "level", level );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "file-name", dossierPart != null ? dossierPart.getPartName() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "part-type", partType );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) null
            _jspx_th_aui_005fa_005f2.setDynamicAttribute(null, "template-no", dossierPart != null ? dossierPart.getTemplateFileNo() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) name = href type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f2.setHref("javascript:void(0);");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f2.setLabel("view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f2.setCssClass("opencps dossiermgt part-file-ctr view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(125,6) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f2.setOnClick(renderResponse.getNamespace() + "viewAttachment(this)" );
            int _jspx_eval_aui_005fa_005f2 = _jspx_th_aui_005fa_005f2.doStartTag();
            if (_jspx_th_aui_005fa_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f2);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f2);
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f2 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(144,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f2.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_OTHER && level > 0 );
          int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
          if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t");
            //  aui:a
            com.liferay.taglib.aui.ATag _jspx_th_aui_005fa_005f3 = (com.liferay.taglib.aui.ATag) _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.get(com.liferay.taglib.aui.ATag.class);
            _jspx_th_aui_005fa_005f3.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fa_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f2);
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f3.setId(String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "dossier-part", String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "dossier-file", String.valueOf(dossierFileId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "file-url", fileURL );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "index", String.valueOf(index) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "group-name", groupName );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "level", level );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "file-name", dossierPart != null ? dossierPart.getPartName() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "part-type", partType );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) null
            _jspx_th_aui_005fa_005f3.setDynamicAttribute(null, "template-no", dossierPart != null ? dossierPart.getTemplateFileNo() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) name = href type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f3.setHref("javascript:void(0);");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f3.setLabel("view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f3.setCssClass("opencps dossiermgt part-file-ctr view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(149,6) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f3.setOnClick(renderResponse.getNamespace() + "viewAttachment(this)" );
            int _jspx_eval_aui_005fa_005f3 = _jspx_th_aui_005fa_005f3.doStartTag();
            if (_jspx_th_aui_005fa_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f3);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f3);
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f3 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(168,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f3.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_PRIVATE);
          int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
          if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f4 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(178,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f4.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_OPTION && level == 0 );
          int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
          if (_jspx_eval_c_005fwhen_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          //  c:when
          com.liferay.taglib.core.WhenTag _jspx_th_c_005fwhen_005f5 = (com.liferay.taglib.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(com.liferay.taglib.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f5.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(188,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f5.setTest(partType == PortletConstants.DOSSIER_PART_TYPE_OPTION && level > 0 );
          int _jspx_eval_c_005fwhen_005f5 = _jspx_th_c_005fwhen_005f5.doStartTag();
          if (_jspx_eval_c_005fwhen_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t<td width=\"50%\" align=\"right\">\n");
            out.write("\t\t\t\t\t\t");
            //  aui:a
            com.liferay.taglib.aui.ATag _jspx_th_aui_005fa_005f4 = (com.liferay.taglib.aui.ATag) _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.get(com.liferay.taglib.aui.ATag.class);
            _jspx_th_aui_005fa_005f4.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fa_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f5);
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f4.setId(String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "dossier-part", String.valueOf(dossierPartId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "dossier-file", String.valueOf(dossierFileId) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "file-url", fileURL );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "index", String.valueOf(index) );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "group-name", groupName );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "level", level );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "file-name", dossierPart != null ? dossierPart.getPartName() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "part-type", partType );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) null
            _jspx_th_aui_005fa_005f4.setDynamicAttribute(null, "template-no", dossierPart != null ? dossierPart.getTemplateFileNo() : StringPool.BLANK );
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) name = href type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f4.setHref("javascript:void(0);");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f4.setLabel("view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f4.setCssClass("opencps dossiermgt part-file-ctr view-attachment");
            // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(193,6) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fa_005f4.setOnClick(renderResponse.getNamespace() + "viewAttachment(this)" );
            int _jspx_eval_aui_005fa_005f4 = _jspx_th_aui_005fa_005f4.doStartTag();
            if (_jspx_th_aui_005fa_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f4);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fa_0026_005ftemplate_002dno_005fpart_002dtype_005fonClick_005flevel_005flabel_005findex_005fid_005fhref_005fgroup_002dname_005ffile_002durl_005ffile_002dname_005fdossier_002dpart_005fdossier_002dfile_005fcssClass_005fnobody.reuse(_jspx_th_aui_005fa_005f4);
            out.write("\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t");
          }
          if (_jspx_th_c_005fwhen_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
          out.write("\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t");
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        out.write("\n");
        out.write("\t\t</tr>\n");
        out.write("\t</table>\n");
        out.write("\n");
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write('\n');
      out.write('\n');
      //  aui:script
      com.liferay.taglib.aui.ScriptTag _jspx_th_aui_005fscript_005f0 = (com.liferay.taglib.aui.ScriptTag) _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse.get(com.liferay.taglib.aui.ScriptTag.class);
      _jspx_th_aui_005fscript_005f0.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fscript_005f0.setParent(null);
      // /html/portlets/dossiermgt/frontoffice/overview_files.jsp(220,0) name = use type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fscript_005f0.setUse("aui-base,aui-io");
      int _jspx_eval_aui_005fscript_005f0 = _jspx_th_aui_005fscript_005f0.doStartTag();
      if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_aui_005fscript_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_aui_005fscript_005f0.doInitBody();
        }
        do {
          out.write("\n");
          out.write("\tAUI().ready(function(A){\n");
          out.write("\t\tvar cancelButton = A.one('#");
          if (_jspx_meth_portlet_005fnamespace_005f0(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("cancel');\n");
          out.write("\t\tif(cancelButton){\n");
          out.write("\t\t\tcancelButton.on('click', function(){\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_portlet_005fnamespace_005f1(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("closeDialog();\n");
          out.write("\t\t\t});\n");
          out.write("\t\t}\n");
          out.write("\t\t\n");
          out.write("\t\t\n");
          out.write("\t});\n");
          out.write("\t\n");
          out.write("\tLiferay.provide(window, '");
          if (_jspx_meth_portlet_005fnamespace_005f2(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("closeDialog', function() {\n");
          out.write("\t\tvar dialog = Liferay.Util.getWindow('");
          if (_jspx_meth_portlet_005fnamespace_005f3(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("dossierFileId');\n");
          out.write("\t\tdialog.destroy(); // You can try toggle/hide whate\n");
          out.write("\t});\n");
          out.write("\t\n");
          out.write("\tLiferay.provide(window, '");
          if (_jspx_meth_portlet_005fnamespace_005f4(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("viewForm', function(e) {\n");
          out.write("\t\t\n");
          out.write("\t\tvar A = AUI();\n");
          out.write("\t\t\n");
          out.write("\t\tvar instance = A.one(e);\n");
          out.write("\t\t\n");
          out.write("\t\tvar dossierPartId = instance.attr('dossier-part');\n");
          out.write("\t\t\n");
          out.write("\t\tdossierFileId = instance.attr('dossier-file');\n");
          out.write("\n");
          out.write("\t\tvar portletURL = Liferay.PortletURL.createURL('");
          out.print( PortletURLFactoryUtil.create(request, WebKeys.PROCESS_ORDER_PORTLET, themeDisplay.getPlid(), PortletRequest.RENDER_PHASE) );
          out.write("');\n");
          out.write("\t\tportletURL.setParameter(\"mvcPath\", \"/html/portlets/processmgt/processorder/dynamic_form.jsp\");\n");
          out.write("\t\tportletURL.setWindowState(\"");
          out.print(LiferayWindowState.POP_UP.toString());
          out.write("\"); \n");
          out.write("\t\tportletURL.setPortletMode(\"normal\");\n");
          out.write("\t\tportletURL.setParameter(\"dossierPartId\", dossierPartId);\n");
          out.write("\t\tportletURL.setParameter(\"dossierFileId\", dossierFileId);\n");
          out.write("\n");
          out.write("\t\t");
          if (_jspx_meth_portlet_005fnamespace_005f5(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("openDossierDialog(portletURL.toString(), '");
          if (_jspx_meth_portlet_005fnamespace_005f6(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("dynamicForm','");
          out.print( UnicodeLanguageUtil.get(pageContext, "view-form") );
          out.write("');\n");
          out.write("\t});\n");
          out.write("\n");
          out.write("\tLiferay.provide(window, '");
          if (_jspx_meth_portlet_005fnamespace_005f7(_jspx_th_aui_005fscript_005f0, _jspx_page_context))
            return;
          out.write("viewAttachment', function(e) {\n");
          out.write("\t\tvar A = AUI();\n");
          out.write("\t\tvar instance = A.one(e);\n");
          out.write("\t\tvar dossierFileId = instance.attr('dossier-file');\n");
          out.write("\t\tvar fileURL = instance.attr('file-url');\n");
          out.write("\t\tif(fileURL == ''){\n");
          out.write("\t\t\talert('");
          out.print( UnicodeLanguageUtil.get(pageContext, "not-attachment-file") );
          out.write("');\n");
          out.write("\t\t\treturn;\n");
          out.write("\t\t}else{\n");
          out.write("\t\t\twindow.open(fileURL, '_blank');\n");
          out.write("\t\t}\n");
          out.write("\t\t\n");
          out.write("\t});\n");
          int evalDoAfterBody = _jspx_th_aui_005fscript_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_aui_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse.reuse(_jspx_th_aui_005fscript_005f0);
        return;
      }
      _005fjspx_005ftagPool_005faui_005fscript_0026_005fuse.reuse(_jspx_th_aui_005fscript_005f0);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f0 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f0.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f0 = _jspx_th_portlet_005fnamespace_005f0.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f0);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f1 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f1.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f1 = _jspx_th_portlet_005fnamespace_005f1.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f1);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f2 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f2.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f2 = _jspx_th_portlet_005fnamespace_005f2.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f2);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f3 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f3.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f3 = _jspx_th_portlet_005fnamespace_005f3.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f3);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f4 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f4.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f4 = _jspx_th_portlet_005fnamespace_005f4.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f4);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f5 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f5.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f5 = _jspx_th_portlet_005fnamespace_005f5.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f5);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f6 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f6.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f6 = _jspx_th_portlet_005fnamespace_005f6.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f6);
    return false;
  }

  private boolean _jspx_meth_portlet_005fnamespace_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fscript_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:namespace
    com.liferay.taglib.portlet.NamespaceTag _jspx_th_portlet_005fnamespace_005f7 = (com.liferay.taglib.portlet.NamespaceTag) _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.get(com.liferay.taglib.portlet.NamespaceTag.class);
    _jspx_th_portlet_005fnamespace_005f7.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fnamespace_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fscript_005f0);
    int _jspx_eval_portlet_005fnamespace_005f7 = _jspx_th_portlet_005fnamespace_005f7.doStartTag();
    if (_jspx_th_portlet_005fnamespace_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fnamespace_005fnobody.reuse(_jspx_th_portlet_005fnamespace_005f7);
    return false;
  }
}
