/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2024-07-30 15:30:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html.portlets.dossiermgt.frontoffice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.portlet.LiferayWindowState;
import org.opencps.dossiermgt.util.DossierMgtUtil;
import org.opencps.util.ActionKeys;
import org.opencps.dossiermgt.permissions.DossierPermission;
import javax.portlet.PortletURL;
import org.opencps.util.PortletUtil;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portlet.PortletPreferencesFactoryUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.util.PortalUtil;
import com.liferay.portal.kernel.dao.search.SearchContainer;

public final class toolbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	private Log _log = LogFactoryUtil.getLog("html.portlets.dossiermgt.frontoffice.toolbar.jsp");

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/init.jsp", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/html/portlets/dossiermgt/frontoffice/../init.jsp", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/opencps-dl-upload.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet-ext.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/opencps-datamgt.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-theme.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-util.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/aui.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-ui.tld", Long.valueOf(1722352539000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-security.tld", Long.valueOf(1722352539000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005frow;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005frow = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.release();
    _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass.release();
    _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar.release();
    _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody.release();
    _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass.release();
    _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005faui_005frow.release();
    _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.release();
    _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField.release();
    _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write('\r');
      out.write('\n');

/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  portlet:defineObjects
      com.liferay.taglib.portlet.DefineObjectsTag _jspx_th_portlet_005fdefineObjects_005f0 = (com.liferay.taglib.portlet.DefineObjectsTag) _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.get(com.liferay.taglib.portlet.DefineObjectsTag.class);
      _jspx_th_portlet_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_portlet_005fdefineObjects_005f0 = _jspx_th_portlet_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_portlet_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.reuse(_jspx_th_portlet_005fdefineObjects_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.reuse(_jspx_th_portlet_005fdefineObjects_005f0);
      javax.portlet.ActionRequest actionRequest = null;
      javax.portlet.ActionResponse actionResponse = null;
      javax.portlet.EventRequest eventRequest = null;
      javax.portlet.EventResponse eventResponse = null;
      com.liferay.portal.kernel.portlet.LiferayPortletRequest liferayPortletRequest = null;
      com.liferay.portal.kernel.portlet.LiferayPortletResponse liferayPortletResponse = null;
      javax.portlet.PortletConfig portletConfig = null;
      java.lang.String portletName = null;
      javax.portlet.PortletPreferences portletPreferences = null;
      java.util.Map portletPreferencesValues = null;
      javax.portlet.PortletSession portletSession = null;
      java.util.Map portletSessionScope = null;
      javax.portlet.RenderRequest renderRequest = null;
      javax.portlet.RenderResponse renderResponse = null;
      javax.portlet.ResourceRequest resourceRequest = null;
      javax.portlet.ResourceResponse resourceResponse = null;
      com.liferay.portal.kernel.util.SearchContainerReference searchContainerReference = null;
      actionRequest = (javax.portlet.ActionRequest) _jspx_page_context.findAttribute("actionRequest");
      actionResponse = (javax.portlet.ActionResponse) _jspx_page_context.findAttribute("actionResponse");
      eventRequest = (javax.portlet.EventRequest) _jspx_page_context.findAttribute("eventRequest");
      eventResponse = (javax.portlet.EventResponse) _jspx_page_context.findAttribute("eventResponse");
      liferayPortletRequest = (com.liferay.portal.kernel.portlet.LiferayPortletRequest) _jspx_page_context.findAttribute("liferayPortletRequest");
      liferayPortletResponse = (com.liferay.portal.kernel.portlet.LiferayPortletResponse) _jspx_page_context.findAttribute("liferayPortletResponse");
      portletConfig = (javax.portlet.PortletConfig) _jspx_page_context.findAttribute("portletConfig");
      portletName = (java.lang.String) _jspx_page_context.findAttribute("portletName");
      portletPreferences = (javax.portlet.PortletPreferences) _jspx_page_context.findAttribute("portletPreferences");
      portletPreferencesValues = (java.util.Map) _jspx_page_context.findAttribute("portletPreferencesValues");
      portletSession = (javax.portlet.PortletSession) _jspx_page_context.findAttribute("portletSession");
      portletSessionScope = (java.util.Map) _jspx_page_context.findAttribute("portletSessionScope");
      renderRequest = (javax.portlet.RenderRequest) _jspx_page_context.findAttribute("renderRequest");
      renderResponse = (javax.portlet.RenderResponse) _jspx_page_context.findAttribute("renderResponse");
      resourceRequest = (javax.portlet.ResourceRequest) _jspx_page_context.findAttribute("resourceRequest");
      resourceResponse = (javax.portlet.ResourceResponse) _jspx_page_context.findAttribute("resourceResponse");
      searchContainerReference = (com.liferay.portal.kernel.util.SearchContainerReference) _jspx_page_context.findAttribute("searchContainerReference");
      out.write('\n');
      out.write('\n');
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = (com.liferay.taglib.theme.DefineObjectsTag) _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.get(com.liferay.taglib.theme.DefineObjectsTag.class);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fliferay_002dtheme_005fdefineObjects_005fnobody.reuse(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      com.liferay.portal.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.model.Company company = null;
      com.liferay.portal.model.Account account = null;
      com.liferay.portal.model.User user = null;
      com.liferay.portal.model.User realUser = null;
      com.liferay.portal.model.Contact contact = null;
      com.liferay.portal.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long scopeGroupId = null;
      com.liferay.portal.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.model.Theme theme = null;
      com.liferay.portal.model.ColorScheme colorScheme = null;
      com.liferay.portal.theme.PortletDisplay portletDisplay = null;
      java.lang.Long portletGroupId = null;
      themeDisplay = (com.liferay.portal.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.model.Company) _jspx_page_context.findAttribute("company");
      account = (com.liferay.portal.model.Account) _jspx_page_context.findAttribute("account");
      user = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      scopeGroupId = (java.lang.Long) _jspx_page_context.findAttribute("scopeGroupId");
      permissionChecker = (com.liferay.portal.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      out.write('\n');
      out.write('\n');

	String currentURL = PortalUtil.getCurrentURL(liferayPortletRequest);
	String keyword = ParamUtil.getString(request, "keywords", StringPool.BLANK);
	String templatePath = portletConfig.getInitParameter("template-path");
	
	String portletResource = ParamUtil.getString(request,"portletResource");
	
	if (Validator.isNotNull(portletResource)) {
		portletPreferences = PortletPreferencesFactoryUtil.getPortletSetup(request, portletResource);
	}

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

	String tabs1 = ParamUtil.getString(request, "tabs1", DossierMgtUtil.TOP_TABS_DOSSIER);
	PortletURL searchURL = renderResponse.createRenderURL();

      out.write('\n');
      out.write('\n');
      //  aui:nav-bar
      com.liferay.taglib.aui.NavBarTag _jspx_th_aui_005fnav_002dbar_005f0 = (com.liferay.taglib.aui.NavBarTag) _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass.get(com.liferay.taglib.aui.NavBarTag.class);
      _jspx_th_aui_005fnav_002dbar_005f0.setPageContext(_jspx_page_context);
      _jspx_th_aui_005fnav_002dbar_005f0.setParent(null);
      // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(38,0) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_aui_005fnav_002dbar_005f0.setCssClass("custom-toolbar");
      int _jspx_eval_aui_005fnav_002dbar_005f0 = _jspx_th_aui_005fnav_002dbar_005f0.doStartTag();
      if (_jspx_eval_aui_005fnav_002dbar_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_aui_005fnav_002dbar_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_aui_005fnav_002dbar_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_aui_005fnav_002dbar_005f0.doInitBody();
        }
        do {
          out.write('\n');
          out.write('	');
          //  aui:nav
          com.liferay.taglib.aui.NavTag _jspx_th_aui_005fnav_005f0 = (com.liferay.taglib.aui.NavTag) _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass.get(com.liferay.taglib.aui.NavTag.class);
          _jspx_th_aui_005fnav_005f0.setPageContext(_jspx_page_context);
          _jspx_th_aui_005fnav_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fnav_002dbar_005f0);
          // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(39,1) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_aui_005fnav_005f0.setId("toolbarContainer");
          // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(39,1) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_aui_005fnav_005f0.setCssClass("nav-display-style-buttons pull-left");
          int _jspx_eval_aui_005fnav_005f0 = _jspx_th_aui_005fnav_005f0.doStartTag();
          if (_jspx_eval_aui_005fnav_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write('\n');
            out.write('	');
            out.write('	');
            //  c:if
            com.liferay.taglib.core.IfTag _jspx_th_c_005fif_005f0 = (com.liferay.taglib.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(com.liferay.taglib.core.IfTag.class);
            _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
            _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fnav_005f0);
            // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(40,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_c_005fif_005f0.setTest(DossierPermission.contains(permissionChecker, scopeGroupId, ActionKeys.ADD_DOSSIER) && tabs1.equals(DossierMgtUtil.TOP_TABS_DOSSIER));
            int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
            if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              out.write("\n");
              out.write("\t\t\t\n");
              out.write("\t\t\t");
              //  portlet:renderURL
              com.liferay.taglib.portlet.RenderURLTag _jspx_th_portlet_005frenderURL_005f0 = (com.liferay.taglib.portlet.RenderURLTag) _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar.get(com.liferay.taglib.portlet.RenderURLTag.class);
              _jspx_th_portlet_005frenderURL_005f0.setPageContext(_jspx_page_context);
              _jspx_th_portlet_005frenderURL_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(42,3) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_portlet_005frenderURL_005f0.setVar("addDossierURL");
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(42,3) name = windowState type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_portlet_005frenderURL_005f0.setWindowState(LiferayWindowState.NORMAL.toString() );
              int _jspx_eval_portlet_005frenderURL_005f0 = _jspx_th_portlet_005frenderURL_005f0.doStartTag();
              if (_jspx_eval_portlet_005frenderURL_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write("\n");
                out.write("\t\t\t\t");
                if (_jspx_meth_portlet_005fparam_005f0(_jspx_th_portlet_005frenderURL_005f0, _jspx_page_context))
                  return;
                out.write("\n");
                out.write("\t\t\t\t");
                //  portlet:param
                com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f1 = (com.liferay.taglib.util.ParamTag) _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.get(com.liferay.taglib.util.ParamTag.class);
                _jspx_th_portlet_005fparam_005f1.setPageContext(_jspx_page_context);
                _jspx_th_portlet_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f0);
                // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(44,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_portlet_005fparam_005f1.setName("backURL");
                // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(44,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_portlet_005fparam_005f1.setValue(currentURL );
                int _jspx_eval_portlet_005fparam_005f1 = _jspx_th_portlet_005fparam_005f1.doStartTag();
                if (_jspx_th_portlet_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_portlet_005fparam_005f1);
                  return;
                }
                _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_portlet_005fparam_005f1);
                out.write("\n");
                out.write("\t\t\t");
              }
              if (_jspx_th_portlet_005frenderURL_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar.reuse(_jspx_th_portlet_005frenderURL_005f0);
                return;
              }
              _005fjspx_005ftagPool_005fportlet_005frenderURL_0026_005fwindowState_005fvar.reuse(_jspx_th_portlet_005frenderURL_005f0);
              java.lang.String addDossierURL = null;
              addDossierURL = (java.lang.String) _jspx_page_context.findAttribute("addDossierURL");
              out.write("\n");
              out.write("\t\t\t");
              //  aui:nav-item
              com.liferay.taglib.aui.NavItemTag _jspx_th_aui_005fnav_002ditem_005f0 = (com.liferay.taglib.aui.NavItemTag) _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody.get(com.liferay.taglib.aui.NavItemTag.class);
              _jspx_th_aui_005fnav_002ditem_005f0.setPageContext(_jspx_page_context);
              _jspx_th_aui_005fnav_002ditem_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(46,3) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_aui_005fnav_002ditem_005f0.setId("addDictItem");
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(46,3) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_aui_005fnav_002ditem_005f0.setLabel("add-dossier");
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(46,3) name = iconCssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_aui_005fnav_002ditem_005f0.setIconCssClass("icon-plus");
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(46,3) name = href type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_aui_005fnav_002ditem_005f0.setHref(addDossierURL );
              int _jspx_eval_aui_005fnav_002ditem_005f0 = _jspx_th_aui_005fnav_002ditem_005f0.doStartTag();
              if (_jspx_th_aui_005fnav_002ditem_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody.reuse(_jspx_th_aui_005fnav_002ditem_005f0);
                return;
              }
              _005fjspx_005ftagPool_005faui_005fnav_002ditem_0026_005flabel_005fid_005ficonCssClass_005fhref_005fnobody.reuse(_jspx_th_aui_005fnav_002ditem_005f0);
              out.write('\n');
              out.write('	');
              out.write('	');
            }
            if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
              return;
            }
            _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
            out.write('\n');
            out.write('	');
          }
          if (_jspx_th_aui_005fnav_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass.reuse(_jspx_th_aui_005fnav_005f0);
            return;
          }
          _005fjspx_005ftagPool_005faui_005fnav_0026_005fid_005fcssClass.reuse(_jspx_th_aui_005fnav_005f0);
          out.write("\n");
          out.write("\t\n");
          out.write("\t");
          //  aui:nav-bar-search
          com.liferay.taglib.aui.NavBarSearchTag _jspx_th_aui_005fnav_002dbar_002dsearch_005f0 = (com.liferay.taglib.aui.NavBarSearchTag) _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass.get(com.liferay.taglib.aui.NavBarSearchTag.class);
          _jspx_th_aui_005fnav_002dbar_002dsearch_005f0.setPageContext(_jspx_page_context);
          _jspx_th_aui_005fnav_002dbar_002dsearch_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fnav_002dbar_005f0);
          // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(55,1) name = cssClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_aui_005fnav_002dbar_002dsearch_005f0.setCssClass("pull-right");
          int _jspx_eval_aui_005fnav_002dbar_002dsearch_005f0 = _jspx_th_aui_005fnav_002dbar_002dsearch_005f0.doStartTag();
          if (_jspx_eval_aui_005fnav_002dbar_002dsearch_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write("\n");
            out.write("\t\t<div class=\"form-search\">\n");
            out.write("\t\t\t");
            //  aui:form
            com.liferay.taglib.aui.FormTag _jspx_th_aui_005fform_005f0 = (com.liferay.taglib.aui.FormTag) _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction.get(com.liferay.taglib.aui.FormTag.class);
            _jspx_th_aui_005fform_005f0.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fnav_002dbar_002dsearch_005f0);
            // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(57,3) name = action type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fform_005f0.setAction( searchURL );
            // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(57,3) name = method type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fform_005f0.setMethod("post");
            // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(57,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fform_005f0.setName("fm");
            int _jspx_eval_aui_005fform_005f0 = _jspx_th_aui_005fform_005f0.doStartTag();
            if (_jspx_eval_aui_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              out.write("\n");
              out.write("\t\t\t\t");
              //  c:if
              com.liferay.taglib.core.IfTag _jspx_th_c_005fif_005f1 = (com.liferay.taglib.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(com.liferay.taglib.core.IfTag.class);
              _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fform_005f0);
              // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(58,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f1.setTest(tabs1.equals(DossierMgtUtil.TOP_TABS_DOSSIER) );
              int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
              if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write("\n");
                out.write("\t\t\t\t\t");

						searchURL.setParameter("mvcPath", templatePath + "frontofficedossierlist.jsp");
						searchURL.setParameter("tabs1", DossierMgtUtil.TOP_TABS_DOSSIER);
					
                out.write("\n");
                out.write("\t\t\t\t\t");
                //  aui:row
                com.liferay.taglib.aui.RowTag _jspx_th_aui_005frow_005f0 = (com.liferay.taglib.aui.RowTag) _005fjspx_005ftagPool_005faui_005frow.get(com.liferay.taglib.aui.RowTag.class);
                _jspx_th_aui_005frow_005f0.setPageContext(_jspx_page_context);
                _jspx_th_aui_005frow_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
                int _jspx_eval_aui_005frow_005f0 = _jspx_th_aui_005frow_005f0.doStartTag();
                if (_jspx_eval_aui_005frow_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  out.write("\n");
                  out.write("\t\t\t\t\t\t");
                  //  aui:col
                  com.liferay.taglib.aui.ColTag _jspx_th_aui_005fcol_005f0 = (com.liferay.taglib.aui.ColTag) _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.get(com.liferay.taglib.aui.ColTag.class);
                  _jspx_th_aui_005fcol_005f0.setPageContext(_jspx_page_context);
                  _jspx_th_aui_005fcol_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005frow_005f0);
                  // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(64,6) name = width type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_aui_005fcol_005f0.setWidth(50);
                  int _jspx_eval_aui_005fcol_005f0 = _jspx_th_aui_005fcol_005f0.doStartTag();
                  if (_jspx_eval_aui_005fcol_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    out.write("\n");
                    out.write("\t\t\t\t\t\t\t");
                    //  aui:select
                    com.liferay.taglib.aui.SelectTag _jspx_th_aui_005fselect_005f0 = (com.liferay.taglib.aui.SelectTag) _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField.get(com.liferay.taglib.aui.SelectTag.class);
                    _jspx_th_aui_005fselect_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_aui_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fcol_005f0);
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(65,7) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_aui_005fselect_005f0.setName("dossierStatus");
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(65,7) name = label type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_aui_005fselect_005f0.setLabel("");
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(65,7) name = inlineField type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_aui_005fselect_005f0.setInlineField(true );
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(65,7) name = inlineLabel type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_aui_005fselect_005f0.setInlineLabel("left");
                    int _jspx_eval_aui_005fselect_005f0 = _jspx_th_aui_005fselect_005f0.doStartTag();
                    if (_jspx_eval_aui_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t\t");
                      if (_jspx_meth_aui_005foption_005f0(_jspx_th_aui_005fselect_005f0, _jspx_page_context))
                        return;
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t\t");

									for(Integer status : PortletUtil.getDossierStatus()){
										
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t\t\t\t\t");
                      //  aui:option
                      com.liferay.taglib.aui.OptionTag _jspx_th_aui_005foption_005f1 = (com.liferay.taglib.aui.OptionTag) _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.get(com.liferay.taglib.aui.OptionTag.class);
                      _jspx_th_aui_005foption_005f1.setPageContext(_jspx_page_context);
                      _jspx_th_aui_005foption_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fselect_005f0);
                      // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(70,11) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_aui_005foption_005f1.setValue( status);
                      int _jspx_eval_aui_005foption_005f1 = _jspx_th_aui_005foption_005f1.doStartTag();
                      if (_jspx_eval_aui_005foption_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        out.print(PortletUtil.getDossierStatusLabel(status, locale) );
                      }
                      if (_jspx_th_aui_005foption_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.reuse(_jspx_th_aui_005foption_005f1);
                        return;
                      }
                      _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.reuse(_jspx_th_aui_005foption_005f1);
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t\t\t\t");

									}
								
                      out.write("\n");
                      out.write("\t\t\t\t\t\t\t");
                    }
                    if (_jspx_th_aui_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField.reuse(_jspx_th_aui_005fselect_005f0);
                      return;
                    }
                    _005fjspx_005ftagPool_005faui_005fselect_0026_005fname_005flabel_005finlineLabel_005finlineField.reuse(_jspx_th_aui_005fselect_005f0);
                    out.write("\n");
                    out.write("\t\t\t\t\t\t");
                  }
                  if (_jspx_th_aui_005fcol_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.reuse(_jspx_th_aui_005fcol_005f0);
                    return;
                  }
                  _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.reuse(_jspx_th_aui_005fcol_005f0);
                  out.write("\n");
                  out.write("\t\t\t\t\t\t");
                  //  aui:col
                  com.liferay.taglib.aui.ColTag _jspx_th_aui_005fcol_005f1 = (com.liferay.taglib.aui.ColTag) _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.get(com.liferay.taglib.aui.ColTag.class);
                  _jspx_th_aui_005fcol_005f1.setPageContext(_jspx_page_context);
                  _jspx_th_aui_005fcol_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005frow_005f0);
                  // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(76,6) name = width type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_aui_005fcol_005f1.setWidth(50);
                  int _jspx_eval_aui_005fcol_005f1 = _jspx_th_aui_005fcol_005f1.doStartTag();
                  if (_jspx_eval_aui_005fcol_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    out.write("\n");
                    out.write("\t\t\t\t\t\t\t");
                    //  liferay-ui:input-search
                    com.liferay.taglib.ui.InputSearchTag _jspx_th_liferay_002dui_005finput_002dsearch_005f0 = (com.liferay.taglib.ui.InputSearchTag) _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody.get(com.liferay.taglib.ui.InputSearchTag.class);
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fcol_005f1);
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(77,7) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setId("keywords1");
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(77,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setName("keywords");
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(77,7) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setTitle("keywords");
                    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(77,7) name = placeholder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_liferay_002dui_005finput_002dsearch_005f0.setPlaceholder( LanguageUtil.get(locale, "keywords") );
                    int _jspx_eval_liferay_002dui_005finput_002dsearch_005f0 = _jspx_th_liferay_002dui_005finput_002dsearch_005f0.doStartTag();
                    if (_jspx_th_liferay_002dui_005finput_002dsearch_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody.reuse(_jspx_th_liferay_002dui_005finput_002dsearch_005f0);
                      return;
                    }
                    _005fjspx_005ftagPool_005fliferay_002dui_005finput_002dsearch_0026_005ftitle_005fplaceholder_005fname_005fid_005fnobody.reuse(_jspx_th_liferay_002dui_005finput_002dsearch_005f0);
                    out.write("\n");
                    out.write("\t\t\t\t\t\t");
                  }
                  if (_jspx_th_aui_005fcol_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.reuse(_jspx_th_aui_005fcol_005f1);
                    return;
                  }
                  _005fjspx_005ftagPool_005faui_005fcol_0026_005fwidth.reuse(_jspx_th_aui_005fcol_005f1);
                  out.write("\n");
                  out.write("\t\t\t\t\t");
                }
                if (_jspx_th_aui_005frow_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  _005fjspx_005ftagPool_005faui_005frow.reuse(_jspx_th_aui_005frow_005f0);
                  return;
                }
                _005fjspx_005ftagPool_005faui_005frow.reuse(_jspx_th_aui_005frow_005f0);
                out.write("\n");
                out.write("\t\t\t\t");
              }
              if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
              out.write("\n");
              out.write("\t\t\t");
            }
            if (_jspx_th_aui_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction.reuse(_jspx_th_aui_005fform_005f0);
              return;
            }
            _005fjspx_005ftagPool_005faui_005fform_0026_005fname_005fmethod_005faction.reuse(_jspx_th_aui_005fform_005f0);
            out.write("\n");
            out.write("\t\t</div>\n");
            out.write("\t");
          }
          if (_jspx_th_aui_005fnav_002dbar_002dsearch_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass.reuse(_jspx_th_aui_005fnav_002dbar_002dsearch_005f0);
            return;
          }
          _005fjspx_005ftagPool_005faui_005fnav_002dbar_002dsearch_0026_005fcssClass.reuse(_jspx_th_aui_005fnav_002dbar_002dsearch_005f0);
          out.write('\n');
          int evalDoAfterBody = _jspx_th_aui_005fnav_002dbar_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_aui_005fnav_002dbar_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_aui_005fnav_002dbar_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass.reuse(_jspx_th_aui_005fnav_002dbar_005f0);
        return;
      }
      _005fjspx_005ftagPool_005faui_005fnav_002dbar_0026_005fcssClass.reuse(_jspx_th_aui_005fnav_002dbar_005f0);
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_portlet_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_portlet_005frenderURL_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  portlet:param
    com.liferay.taglib.util.ParamTag _jspx_th_portlet_005fparam_005f0 = (com.liferay.taglib.util.ParamTag) _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.get(com.liferay.taglib.util.ParamTag.class);
    _jspx_th_portlet_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_portlet_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_portlet_005frenderURL_005f0);
    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(43,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f0.setName("mvcPath");
    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(43,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_portlet_005fparam_005f0.setValue("/html/portlets/dossiermgt/frontoffice/frontofficeservicelist.jsp");
    int _jspx_eval_portlet_005fparam_005f0 = _jspx_th_portlet_005fparam_005f0.doStartTag();
    if (_jspx_th_portlet_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_portlet_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fportlet_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_portlet_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_aui_005foption_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  aui:option
    com.liferay.taglib.aui.OptionTag _jspx_th_aui_005foption_005f0 = (com.liferay.taglib.aui.OptionTag) _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.get(com.liferay.taglib.aui.OptionTag.class);
    _jspx_th_aui_005foption_005f0.setPageContext(_jspx_page_context);
    _jspx_th_aui_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005fselect_005f0);
    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(66,8) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_aui_005foption_005f0.setValue("-1");
    int _jspx_eval_aui_005foption_005f0 = _jspx_th_aui_005foption_005f0.doStartTag();
    if (_jspx_eval_aui_005foption_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_meth_liferay_002dui_005fmessage_005f0(_jspx_th_aui_005foption_005f0, _jspx_page_context))
        return true;
    }
    if (_jspx_th_aui_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.reuse(_jspx_th_aui_005foption_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005faui_005foption_0026_005fvalue.reuse(_jspx_th_aui_005foption_005f0);
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_aui_005foption_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f0 = (com.liferay.taglib.ui.MessageTag) _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody.get(com.liferay.taglib.ui.MessageTag.class);
    _jspx_th_liferay_002dui_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005foption_005f0);
    // /html/portlets/dossiermgt/frontoffice/toolbar.jsp(66,31) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f0.setKey("all");
    int _jspx_eval_liferay_002dui_005fmessage_005f0 = _jspx_th_liferay_002dui_005fmessage_005f0.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_liferay_002dui_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fliferay_002dui_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_liferay_002dui_005fmessage_005f0);
    return false;
  }
}
