/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package org.opencps.sample.staff.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Staff service. Represents a row in the &quot;staff_Staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.sample.staff.model.impl.StaffModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.sample.staff.model.impl.StaffImpl}.
 * </p>
 *
 * @author trungnt
 * @see Staff
 * @see org.opencps.sample.staff.model.impl.StaffImpl
 * @see org.opencps.sample.staff.model.impl.StaffModelImpl
 * @generated
 */
public interface StaffModel extends BaseModel<Staff>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff model instance should use the {@link Staff} interface instead.
	 */

	/**
	 * Returns the primary key of this staff.
	 *
	 * @return the primary key of this staff
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staff.
	 *
	 * @param primaryKey the primary key of this staff
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the staff ID of this staff.
	 *
	 * @return the staff ID of this staff
	 */
	public long getStaffId();

	/**
	 * Sets the staff ID of this staff.
	 *
	 * @param staffId the staff ID of this staff
	 */
	public void setStaffId(long staffId);

	/**
	 * Returns the group ID of this staff.
	 *
	 * @return the group ID of this staff
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this staff.
	 *
	 * @param groupId the group ID of this staff
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this staff.
	 *
	 * @return the company ID of this staff
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this staff.
	 *
	 * @param companyId the company ID of this staff
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this staff.
	 *
	 * @return the user ID of this staff
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this staff.
	 *
	 * @param userId the user ID of this staff
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this staff.
	 *
	 * @return the user uuid of this staff
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this staff.
	 *
	 * @param userUuid the user uuid of this staff
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this staff.
	 *
	 * @return the user name of this staff
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this staff.
	 *
	 * @param userName the user name of this staff
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this staff.
	 *
	 * @return the create date of this staff
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this staff.
	 *
	 * @param createDate the create date of this staff
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this staff.
	 *
	 * @return the modified date of this staff
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this staff.
	 *
	 * @param modifiedDate the modified date of this staff
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the department ID of this staff.
	 *
	 * @return the department ID of this staff
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this staff.
	 *
	 * @param departmentId the department ID of this staff
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the full name of this staff.
	 *
	 * @return the full name of this staff
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this staff.
	 *
	 * @param fullName the full name of this staff
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the birth day of this staff.
	 *
	 * @return the birth day of this staff
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this staff.
	 *
	 * @param birthDay the birth day of this staff
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Returns the address of this staff.
	 *
	 * @return the address of this staff
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this staff.
	 *
	 * @param address the address of this staff
	 */
	public void setAddress(String address);

	/**
	 * Returns the email of this staff.
	 *
	 * @return the email of this staff
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this staff.
	 *
	 * @param email the email of this staff
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone number of this staff.
	 *
	 * @return the phone number of this staff
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this staff.
	 *
	 * @param phoneNumber the phone number of this staff
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the position of this staff.
	 *
	 * @return the position of this staff
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this staff.
	 *
	 * @param position the position of this staff
	 */
	public void setPosition(String position);

	/**
	 * Returns the description of this staff.
	 *
	 * @return the description of this staff
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this staff.
	 *
	 * @param description the description of this staff
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.sample.staff.model.Staff staff);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.sample.staff.model.Staff> toCacheModel();

	@Override
	public org.opencps.sample.staff.model.Staff toEscapedModel();

	@Override
	public org.opencps.sample.staff.model.Staff toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}